### ISSUE TITLE
Dragons have no animation.

### ISSUE THREAD

**Issue by SchaiRand** [Monitor144hz/Pandora-Behaviour-Engine-Plus#79]
After running Pandora, dragons stopped animating. Engine.log pointed to a fatal error regarding dragon behaviors.
[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14067177/Engine.log)

**Comment by SchaiRand** [comment]
![SkyrimSE 2024-01-26 23-27-37](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/157286364/499db110-538b-475c-9d09-1af3632e49f8)
I forgot to attach image, this is a dragon that is supposed to be flying but there's no flying animation, thus stuck in that default pose.

**Comment by Kyationa** [comment]
> ![SkyrimSE 2024-01-26 23-27-37](https://private-user-images.githubusercontent.com/157286364/300045525-499db110-538b-475c-9d09-1af3632e49f8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMjA3NDksIm5iZiI6MTcwNjMyMDQ0OSwicGF0aCI6Ii8xNTcyODYzNjQvMzAwMDQ1NTI1LTQ5OWRiMTEwLTUzOGItNDc1Yy05ZDA5LTFhZjM2MzJlNDlmOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QwMTU0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWE5YjQ5N2RjN2M5ZDFiMDM5NDhiN2Q3YjA3MDA0NTM1MTI0ZmJmNWRmZjI0NTgyZTFmMmJmYWRlYTVlZWU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kDQOq3wZ4YTyYPChLcjS_zyO_ryQvxIUCbMfPSf_gdM) I forgot to attach image, this is a dragon that is supposed to be flying but there's no flying animation, thus stuck in that default pose.

do you have any mods that alter dragons? if not delete output and rerun it should fix the issue

**Comment by Kyationa** [comment]
also all the old fnis ports you don't need them at all as pandora does that for you in latest version

**Comment by SchaiRand** [comment]
> also all the old fnis ports you don't need them at all as pandora does that for you in latest version
I only have KS Dragon Overhaul 2 and GoT Dragons installed. Which one should I uninstall?

**Comment by Kyationa** [comment]
> > also all the old fnis ports you don't need them at all as pandora does that for you in latest version
> 
> I only have KS Dragon Overhaul 2 and GoT Dragons installed. Which one should I uninstall?

they both modify dragons in some way so it would be up to you which one you would remove test with one disabled and then try the other just in between each try delete the output so there is less chance of issues

**Comment by SchaiRand** [comment]
> they both modify dragons in some way so it would be up to you which one you would remove test with one disabled and then try the other just in between each try delete the output so there is less chance of issues

I tried disabling all dragon related mods and delete all of Pandora's output as well, I still get the Fatal error related to dragon behavior in Engine.log.

**Comment by Kyationa** [comment]
huh weird

**Comment by SchaiRand** [comment]
Dragon error is no longer observed with Pandora 1.1.3 and newest XPMSE patch, I will close this issue.
